# Generated by Django 3.0.5 on 2021-04-29 07:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('Assesment_id', models.AutoField(primary_key=True, serialize=False)),
                ('S_Date', models.DateTimeField(blank=True, default=datetime.date, null=True)),
                ('E_Date', models.DateTimeField(blank=True, default=datetime.date, null=True)),
                ('Desc', models.CharField(default='', max_length=500)),
                ('Assessment_Type', models.CharField(default='', max_length=100)),
                ('Tittle', models.CharField(default='', max_length=200)),
                ('Created_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('C_ID', models.AutoField(primary_key=True, serialize=False)),
                ('C_logo', models.ImageField(upload_to='images')),
                ('C_Name', models.CharField(default='', max_length=200)),
                ('C_Website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='template_tracking',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_path', models.CharField(default='', max_length=100)),
                ('template_name', models.CharField(default='', max_length=200)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RT.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(default='', max_length=100)),
                ('company_email', models.EmailField(max_length=80)),
                ('company_contact_no', models.CharField(default='', max_length=12)),
                ('Project_type', models.CharField(default='', max_length=100)),
                ('Project_Desc_or_Scope', models.CharField(default='', max_length=500)),
                ('Start_date', models.DateTimeField(blank=True, default=datetime.date, null=True)),
                ('End_date', models.DateTimeField(blank=True, default=datetime.date, null=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RT.Company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('Finding_id', models.AutoField(primary_key=True, serialize=False)),
                ('Finding_Title', models.CharField(default='', max_length=100)),
                ('Owasp_cat', models.CharField(default='', max_length=100)),
                ('Desc', models.CharField(default='', max_length=300)),
                ('Technical_impact', models.CharField(default='', max_length=500)),
                ('Business_impact', models.CharField(default='', max_length=500)),
                ('CVSS_score', models.FloatField()),
                ('CVSS_vector', models.CharField(default='', max_length=100)),
                ('Severity', models.CharField(default='', max_length=100)),
                ('Afftected_resource', models.CharField(default='', max_length=100)),
                ('Affected_parameter', models.CharField(default='', max_length=100)),
                ('Remediation', models.CharField(default='', max_length=100)),
                ('A_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RT.Assessment')),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RT.Company')),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RT.Project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assesment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RT.Assessment')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='Project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RT.Project'),
        ),
    ]
